name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: password
    steps:
      - uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Migrate database
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/newsletter
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=0.2.0 sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh
      - name: Check sqlx metadata file
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/newsletter
        run: cargo sqlx prepare --check -- --bin zero2prod
      - uses: actions-rs/cargo@v1
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/newsletter
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: password
    steps:
      - uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Migrate database
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: password
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=0.2.0 sqlx-cli --no-default-features --features postgres
          SKIP_DOCKER=true ./scripts/init_db.sh
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/newsletter
        with:
          command: clippy
          args: -- -D warnings

